---
- name: Setup users and ssh configuration
  hosts: nginx-server
  vars_files:
    - vars.yaml
  become: true
  tasks:
    - name: Add users with group
      user:
        name: "{{ item.name }}"
        system: "{{ item.sudoer }}"
        shell: "/bin/bash"
        append: yes
        groups: "{{ item.group }}"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: on_create
        create_home: "{{ item.create_home }}"
      when: item.group is defined
      with_items: "{{ users }}"

    - name: Add users without group
      user:
        name: "{{ item.name }}"
        system: "{{ item.sudoer }}"
        shell: "/bin/bash"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: on_create
        create_home: "{{ item.create_home }}"
      when: item.group is not defined
      with_items: "{{ users }}"

    - name: Add to sudoers
      copy:
        dest: /etc/sudoers.d/{{ item.name }}
        content: |
                {{ item.name }}  ALL=(ALL) ALL
                {{ item.name }}  ALL=(root) NOPASSWD:/usr/bin/supervisorctl
                #
      when: item.sudoer
      with_items: "{{ users }}"

    - name: "Copy the authorized key file from"
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', '{{ ssh_public_key }}') }}"
      when: item.sudoer
      with_items: "{{ users }}"